# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Username',
            field=models.CharField(default=b'Name', max_length=16),
        ),
    ]
