# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
