# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
